theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: QVAR Hoops
description: Umair Siddique's Project for UCLA ECEM202A/CSM213A (Fall 2023)
